# name: Build & Push Backend Image

# on:
#   push:
#     branches: [main]
#     paths:
#       - "backend/main/**"

# jobs:
#   docker:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build & Push
#         uses: docker/build-push-action@v5
#         with:
#           context: backend/main
#           file: backend/main/Dockerfile
#           push: true
#           tags: |
#             ${{ secrets.DOCKERHUB_USERNAME }}/narad-main
#             ${{ secrets.DOCKERHUB_USERNAME }}/narad-main:${{ github.sha }}
